### ISSUE TITLE
Plugin is not working in Webstorm

### ISSUE THREAD

**Issue by pierDipi** [redhat-developer/intellij-knative#111]
**Steps to reproduce**

1. Install plugin in Webstorm and restart IDE
![image](https://user-images.githubusercontent.com/33736985/155340714-0f1af9d5-0cf3-4943-adb6-da260c925e20.png)
1. File -> New Project
![image](https://user-images.githubusercontent.com/33736985/155340877-49ff7bdb-2d87-4dca-af47-0689a7d062ef.png)
1. There is no Function project

**Comment by pierDipi** [comment]
I tried in Webstorm because [the plugin page says](https://plugins.jetbrains.com/plugin/16476-knative-by-red-hat):

> Compatible with IntelliJ IDEA (Ultimate, Community, Educational), Android Studio, AppCode, CLion, Code With Me Guest, DataGrip, DataSpell, GoLand, JetBrains Client, MPS, PhpStorm, PyCharm (Professional, Community, Educational), Rider, RubyMine, **WebStorm**

**Comment by lstocchi** [comment]
Thanks @pierDipi for opening this, I was able to replicate it. It looks like the extension point we extend is only used by IntelliJ :thinking:  Sorry for the trouble, we'll fix it asap. If you open a function in the IDE you should be able to use the other features though :crossed_fingers:
