### ISSUE TITLE
kn CLI not found but I have it installed and it's available in path

### ISSUE THREAD

**Issue by pierDipi** [redhat-developer/intellij-knative#112]
**Steps to reproduce**
- Follow these steps to get around the other issue https://github.com/redhat-developer/intellij-knative/issues/111#issuecomment-1048945863
- Open Knative panel on the left (in Webstorm)
![image](https://user-images.githubusercontent.com/33736985/155553635-e590166e-d255-4948-a269-be8da318a2b2.png)
- I do have `kn` installed (my `kn` CLI is built from source using `go install`, so it doesn't have version, build date, etc, maybe that's the problem?)
```
$ kn version
Version:      
Build Date:   
Git Revision: 
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving )
* Eventing
  - sources.knative.dev/v1 (knative-eventing )
  - eventing.knative.dev/v1 (knative-eventing )
```

**Comment by pierDipi** [comment]
cc @lstocchi

**Comment by pierDipi** [comment]
after clicking `no` to the `kn tool required` panel, I get the same for `func` but I have `func`:
```
$ kn func
Serverless functions

Create, build and deploy functions in serverless containers for multiple runtimes on Knative

Usage:
  func [command]

Examples:

# Create a node function called "node-sample" and enter the directory
func create myfunc && cd myfunc

# Build the container image, push it to a registry and deploy it to the connected Knative cluster
# (replace <registry/user> with something like quay.io/user with an account that have you access to)
func deploy --registry <registry/user>

# Curl the service with the service URL
curl $(kn service describe myfunc -o url)


Available Commands:
  build       Build a function project as a container image
  completion  Generate completion scripts for bash, fish and zsh
  config      Configure a function
  create      Create a Function Project
  delete      Undeploy a function
  deploy      Deploy a function
  emit        Emit a CloudEvent to a function endpoint
  help        Help about any command
  info        Show details of a function
  list        List functions
  repository  Manage installed template repositories
  run         Run the function locally
  version     Show the version

Flags:
  -h, --help      help for func
  -v, --verbose   print verbose logs
      --version   version for func

Use "func [command] --help" for more information about a command.
```

**Comment by lstocchi** [comment]
Hey @pierDipi, the plugin looks for the cli in PATH and then check its version. If this doesn't match with the version the plugin should use it will ask you to download it. So currently the plugin needs v. 0.21 for kn cli and 0.19 for func cli, if you have older/newer versions of them or the version is empty as your case it will not be recognized by the plugin. 

I have opened an issue in the common lib that handles this to create a better message so the user is not lost https://github.com/redhat-developer/intellij-common/issues/129 but, aside that, the behavior is correct.

**Comment by lstocchi** [comment]
Usually we try to keep the cli updated to the latest version. This plugin has a troubled history so we missed some releases but this should be fixed soon, at least for serverless functions where there will be active support.

**Comment by pierDipi** [comment]
I see, thanks!

Feel free to close this issue unless you want to keep it open for tracking https://github.com/redhat-developer/intellij-common/issues/129.

**Comment by lstocchi** [comment]
@pierDipi I'm going to close it as we made a new release with the new cli download mechanism in it. Now the plugin tries to discover if the cli needed (the version the plugin needs to work) is within PATH or it was downloaded previously, otherwise it downloads it automatically without asking confirmation to the user. Let us know if you face any other issues. Thanks for your precious help!!
