### ISSUE TITLE
Verify latest service is always first

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-knative#12]
Not sure if this is a real issue or it is because my cluster is dirty. But i had some issue by modifying the service and i ended up with this situation.
![image](https://user-images.githubusercontent.com/49404737/109803479-64182100-7c21-11eb-8a17-4922f8967963.png)

The last 2 revisions are invalid but they are in first positions. We should keep the latest revision to the top and maybe color in red revisions that are not working :man_shrugging:

**Comment by lstocchi** [comment]
I don't have any strong opinion on this. Ok yellow for me :+1:

**Comment by evidolob** [comment]
I think we should sort revisions on `serving.knative.dev/configurationGeneration` label - the newest on top
