### ISSUE TITLE
Add support for func cli M1 build

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-knative#145]
The 0.23.0 release mentions that they now support M1 build for macOS, but the binary is missing from the release. I have raised an issue upstream for the same. Once fixed we need to update our func.json with the darwin-arm64 entry.

Upstream Issue: https://github.com/knative-sandbox/kn-plugin-func/issues/955

**Comment by jeffmaury** [comment]
M1 binary is available now: https://github.com/knative-sandbox/kn-plugin-func/releases/tag/v0.23.1
