### ISSUE TITLE
Update func cli to 1.7.0 & kn to 1.7.0 version

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-knative#213]
As the func CLI version & kn CLI is updated to 1.7.0, the extension should support that.

Func CLI available at: https://github.com/knative/func/releases/tag/knative-v1.7.0

kn CLI: https://github.com/knative/client/releases/tag/knative-v1.7.0

**Comment by lstocchi** [comment]
func cli already updated by https://github.com/redhat-developer/intellij-knative/pull/212
