### ISSUE TITLE
Plugin Shows in Goland Marketplace, but Fails to Install

### ISSUE THREAD

**Issue by acornett21** [redhat-developer/intellij-knative#218]
The plugin shows in the Marketplace for Goland, but when trying to install it fails. Please see screen shots below

![image](https://user-images.githubusercontent.com/88156657/197885469-f51d2659-19e4-4884-ab07-d79eba62b17b.png)

**Comment by rmarting** [comment]
Same issue in this IntelliJ IDEA version:

```text
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.16-200.fc36.x86_64
Current Desktop: GNOME
```

**Comment by lstocchi** [comment]
@acornett21 @rmarting thanks for notifying us and sorry for the trouble. A new release with a fix has just been made. It should be visible soon on the marketplace. Thanks!!

**Comment by rmarting** [comment]
What is the ETA for that new release?

**Comment by lstocchi** [comment]
Usually it takes 1-2 days to be released by the Jetbrains team

**Comment by mohitsuman** [comment]
@rmarting The new version 1.3.1 is now available in the Marketplace. Please give it a try.
