### ISSUE TITLE
Create service

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-knative#5]
As I user, I should be able to create a service.

Should probably lead to a default YAML payload to be edited by user

**Comment by evidolob** [comment]
@jeffmaury @lstocchi Should we use YAML or we can build some sort of UI for adding service?
As it requires to provide name of service and docker image, with optional env variables: https://knative.dev/docs/serving/samples/hello-world/helloworld-go/#deploying

**Comment by evidolob** [comment]
vscode-knative use [QuickInput](https://code.visualstudio.com/api/references/vscode-api#QuickInput) to create service
<img width="710" alt="Screenshot 2021-03-10 at 10 36 14" src="https://user-images.githubusercontent.com/929743/110600294-726bbd00-818c-11eb-93ed-c934ce773983.png">

**Comment by lstocchi** [comment]
During the asparta bug triage we talked about it with Jeff. We came up with the idea to create a wizard/dialog which contains two different views/tabs. 
The first, a simplified version for newbies, with input/textboxes where to add values for basic args (e.g image url -> textbox where to insert the image url).
The second, for expert users, with an editor where they can edit YAML directly.
