### ISSUE TITLE
Update service

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-knative#6]
As a user, I should be able to update a service.

**Comment by lstocchi** [comment]
This is the discussion that went on in vscode https://github.com/talamer/vscode-knative/issues/27. 
Opposite to the `create new service` action, i guess, we shouldn't show any dialog and allow users to edit yaml directly into the IDE editor.
Any other idea on it? @evidolob @jeffmaury

**Comment by evidolob** [comment]
+1 to allow editing service in editor
