### ISSUE TITLE
Service does not open on click

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/intellij-knative#76]
Clicking expands the Service to reveal the Revisions. A service is a parent but also a file. 

I do not know if it is possible in IntelliJ, can you click on an arrow icon to expand and click on the name to open?
Even double click to open is better then opening only via context menu.

**Comment by lstocchi** [comment]
@evidolob i guess we already solved this. Atleast in linux it works. Can you please verify on Mac?

**Comment by evidolob** [comment]
It works on mac

**Comment by mohitsuman** [comment]
@lstocchi Should we close this issue if this works on the supported platforms ?
