### ISSUE TITLE
Support configuration of functions for env and volumes

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-knative#91]
Integrate Serverless Functions UI workflow to support configuration for env variables and volumes.

- [ ] Allow the user to select the config options that manages the configuration of the Function project in the current directory.

**_Acceptance Criteria_**: The user may specify a path to the project directory and then submit command operates on the configuration specified in `func.yaml` configuration file. Users need to deploy or update the function with func deploy in order to apply the updated configuration to the deployed function

- [x] Configure environment variables

**_Acceptance Criteria_**: Allow `Add` and `Remove` Environment variables to the function configuration

- [ ] Configure volumes

**_Acceptance Criteria_**: Allow `Add` and `Remove` Volumes to the function configuration

**Comment by lstocchi** [comment]
Closing it as #102 and #103 were merged :rocket:
