### ISSUE TITLE
Track function run session to stop it from the plugin

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-knative#93]
Track function run sessions as this will spawn an infinite process so we should be able to stop them

**Comment by lstocchi** [comment]
After talking with the serverless team they said they are going to see how to handle it. Maybe by closing the container when the pipe i/o gets closed. Keeping it blocked for now.

**Comment by matejvasek** [comment]
Could you SIGINT or SIGTERM the process?

**Comment by matejvasek** [comment]
This should be fixed in the common red hat intellij library: https://github.com/redhat-developer/intellij-common/issues/135

**Comment by matejvasek** [comment]
https://github.com/redhat-developer/intellij-common/pull/136

**Comment by matejvasek** [comment]
Can we close this now @lstocchi ?

**Comment by lstocchi** [comment]
yes @matejvasek this should solve our issue. Thanks again :pray:
