### ISSUE TITLE
Allow users to manage set of installed repositories for creating functions.

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-knative#97]
Manages template repositories installed on disk.

1. Allow the user to specify the repository location and use the --repository flag. Once added, a template from the repository can be used when creating a new Function.

_Acceptance Criteria_: The Repository Flag: Installing repositories locally is optional. To use a template from a remote repository directly, it is possible to use the --repository flag on create. This leaves the local disk untouched. For example, To create a Function using the Boson Project Hello-World template without installing the template repository locally, use the --repository (-r) flag on create:

- [ ] Add Repository: Add a new repository to the installed set.
- [ ] List Repository: List all available repositories, including the installed default repository.
- [ ] Rename Repository: Rename a previously installed repository from. Only installed repositories can be renamed. 
- [ ] Remove Repository: Remove a repository by name. Removes the repository from local storage entirely. 

Reference: https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/reference/func_repository.md

**Comment by lstocchi** [comment]
@mohitsuman Sudhir found many issues on this part related to functions. For example, when you add a repo, you are asked to add a name and a url, but then there is no way to retrieve the URLs for old-created repo. The cli has a flag to do it but it's not working properly. (-> https://github.com/knative-sandbox/kn-plugin-func/issues/891) or it still doesn't provide a way to retrieve languages and templates from a custom repo (https://github.com/knative-sandbox/kn-plugin-func/issues/874). Do we want to provide a temporary solution or block it until these issues are fixed?

In my mind the workflow was like the gif below in IJ. You open the wizard related to repo, where you can create/delete them and also edit it by clicking on an item. When clicking, a panel, with all the editable fields, is opened. But this is already not possible as the URL textfield will be always empty.
![repo_state](https://user-images.githubusercontent.com/49404737/157652329-c9d1bbb4-bf53-4799-aa1d-082babcc4fa4.gif)
cc @sudhirverma
